name: 部署到 GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 构建 Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm # 使用 npm 缓存

      - name: 安装依赖
        run: |
          cd my-website # 切换到包含 Docusaurus 项目的文件夹
          npm install # 使用 npm 安装依赖

      - name: 构建网站
        run: |
          cd my-website # 切换到包含 Docusaurus 项目的文件夹
          npm run build # 使用 npm 构建网站

      - name: 上传构建制品
        uses: actions/upload-pages-artifact@v3
        with:
          path: my-website/build # 确保此路径指向构建输出

  deploy:
    name: 部署到 GitHub Pages
    needs: build

    permissions:
      pages: write # 以部署到 Pages
      id-token: write # 以验证部署来自正确的源

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


